### ISSUE TITLE
Deleting some data files to make the git clone action faster

### ISSUE THREAD

**Issue by dhrbn** [populse/populse_sandbox#19]
The downloading of Populse - MIA takes quite a while due to the amount of test data (data_tests directory is almost 4Go in size). I think it should be appropriate to delete them from the GitHub repository (for the ones that are not used in the test for CI). @servoz is it ok for you?

**Comment by servoz** [comment]
This a very interesting/important question ! We have to think about the best solution including the possibility to install a "light" and a "heavy" version. Fortunately, if we stay on the 1.0 release in 2 months, we have yet some times to make a decision on this important topic !

**Comment by dhrbn** [comment]
I agree with both of you! I have just removed some Bruker files that were copies of other files in data_tests, they were used to test the importation in the database and are now useless (cf. the corresponding commit https://github.com/populse/populse_sandbox/commit/81760cbbb91f18660e96b5b183476484e0744698). Now the size of the data_tests directory is 551Mo which is quite ok I guess. I do not close this issue for now to remind that some questions have to be answered after the 1.0 release

**Comment by servoz** [comment]
As a test of [Git LFS](https://github.com/git-lfs/git-lfs), the large files in the data_tests directory of the populse_mia repository  are now stored with Git LFS.

It seems that all is fine, except that currently the actual size of the populse mia repository stay the same, [because history has not yet been rewritten from the beginning](https://github.com/git-lfs/git-lfs/issues/3609).

Currently this is not an emergency because the size of our repository does not exceed [the limit imposed by GitHub](https://help.github.com/en/articles/what-is-my-disk-quota).

If necessary, as everything seems to be in place in the LFS side, it will be enough to [rewrite the story from the beginning](https://github.com/git-lfs/git-lfs/issues/326).

I didn't yet take the time to read everything it's needed to know in detail before making the final jump ...

**Comment by denisri** [comment]
I have a bit left populse_mia on a shelf lately, and I have just been trying to catch up with the move to git-lfs in the last days (also to adapt our build / update system to it). I have done several trials to clone using git-lfs and to sync my personal fork. I think I have succeeded at last, and I also fixed a few things in the .gitattributes patterns to make it work.
But just now something very strange has just happened: on github the commits history seems to be erased after april 23 ! It used to be OK one hour or so earlier but things seems to have been lost... And my fork has gone out of sync again.
I still have the more recent commits on my fork, if it can help restoring the repository, but what can have happened ? Maybe it's just github mirrors which got desynchronized (I think it has already happened) ? Or someone did something wrong with a forced push ? Anyway it's rather frightening...
Do you see the same thing ?

**Comment by servoz** [comment]
Oh sorry for that! We decided to go back before rewriting the history. Please wait a bit, we will work tomorrow to make everything clean again ...

**Comment by denisri** [comment]
If it's deliberate and things are not lost, then it's OK for me...

**Comment by servoz** [comment]
So, following the rewriting of history (it was all my fault!), all the checks we had done seemed to indicate that nothing had been lost... but I was a little stressed to observe a problem in the future due to an inconsistency in history.... 

So yesterday afternoon, we rolled back the master branch of populse_mia on THE  commit JUST BEFORE rewriting. This morning, we added the rest of the story after this commit. On our side things seem okay.

Don't hesitate to tell us if there's a problem.

To respect your contribution as an author, we have not added your two commits from yesterday (vide infra). We let you push them.

About the one on the .gitattributes file, it seems to me that the current one does the job, but if I'm wrong, don't hesitate to actually make your modification again! 

I think that following this incident, the best thing to do would be to go back to fresh branches for all existing ones (I will send a message to all the team for this)

```
commit 4407981c0c1a6e1f155180722389519c97433444
Author: Denis Rivière <denis.riviere.gm@gmail.com>
Date:   Thu May 9 11:38:28 2019 +0200

    replaced the very violent sys.exit() by an exception when python version is not suitable

diff --git a/python/populse_mia/info.py b/python/populse_mia/info.py
index abdca34f..5b6a1adb 100644
--- a/python/populse_mia/info.py
+++ b/python/populse_mia/info.py
@@ -90,8 +90,8 @@ elif sys.version_info >= (3 , 6):
 ]
 
 else:
-    sys.exit("The populse_mia is ensured to work with Python >= 3.5")
-    
+    raise ImportError("The populse_mia is ensured to work with Python >= 3.5")
+
 EXTRA_REQUIRES = {
     'doc': [
         'sphinx>=1.0',

```

```
commit d35408b34aecd10ade9d552a2188410ef21001a3 (HEAD -> master, origin/master, origin/HEAD)
Author: Denis Rivière <denis.riviere.gm@gmail.com>
Date:   Thu May 9 15:30:03 2019 +0200

    fixed git lfs patterns

diff --git a/.gitattributes b/.gitattributes
index fcd5dfbc..b9c9ca79 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,7 +1,7 @@
 data_tests/** filter=lfs diff=lfs merge=lfs -text
-data_tests/Bruker_files filter=lfs diff=lfs merge=lfs -text
-data_tests/Nifti_files filter=lfs diff=lfs merge=lfs -text
-data_tests/Philips_files filter=lfs diff=lfs merge=lfs -text
-data_test filter=lfs diff=lfs merge=lfs -text
-resources/mia filter=lfs diff=lfs merge=lfs -text
-resources/spm12 filter=lfs diff=lfs merge=lfs -text
+data_tests/Bruker_files/** filter=lfs diff=lfs merge=lfs -text
+data_tests/Nifti_files/** filter=lfs diff=lfs merge=lfs -text
+data_tests/Philips_files/** filter=lfs diff=lfs merge=lfs -text
+data_test/** filter=lfs diff=lfs merge=lfs -text
+resources/mia/** filter=lfs diff=lfs merge=lfs -text
+resources/spm12/** filter=lfs diff=lfs merge=lfs -text
```

**Comment by denisri** [comment]
I could clone the new repository without error, and the .gitattributes seems OK now (yesterday the clone left lots of staged files, marking all binary files to be converted from lfs to git because they were not recognized in .gitattributes, today it's OK).
I'll have to sync/merge my personal fork and personal branches again (I had some unfinished work going on) but it should not be a problem.

**Comment by servoz** [comment]
Great! you know what ??? I am happy ...
